name: Dastardly Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  dastardly_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker build -t vulnerable-app .
          docker run -d -p 8000:8000 --name vuln-container vulnerable-app

      - name: Wait for Application to be Ready
        run: |
          echo "Waiting for application to start..."
          sleep 10  # Adjust this based on application startup time

      - name: Run Dastardly Scan
        run: |
          docker run --rm -v $(pwd):/dastardly-output dastardly scan http://localhost:8000 > dastardly-report.html

      - name: Commit and Push Dastardly Report
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dastardly-report.html
          git commit -m 'Add Dastardly scan report'
          git pull --rebase origin master
          git push origin master
